<?php

use App\Http\Controllers\Api\V1\EventController;
use App\Http\Controllers\Api\V1\EventChainController;
use App\Http\Controllers\Api\V1\HealthController;
use App\Http\Controllers\Api\V1\IndexController;
use App\Http\Controllers\Api\V1\NewsController;
use App\Http\Controllers\Api\V1\NotificationChannelCredentialController;
use App\Http\Controllers\Api\V1\NotificationTemplateController;
use App\Http\Controllers\Api\V1\OpsTaskController;
use App\Http\Controllers\Api\V1\SecurityController;
use App\Http\Controllers\Api\V1\SignalDeliveryController;
use App\Http\Controllers\Api\V1\SignalOperationController;
use App\Http\Controllers\Api\V1\SignalController;
use App\Http\Controllers\Api\V1\SignalSubscriptionController;
use App\Http\Controllers\Api\V1\StrategyWorkspaceController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::get('/health', HealthController::class);
    Route::get('/ops/tasks', [OpsTaskController::class, 'index']);
    Route::get('/ops/task-runs', [OpsTaskController::class, 'runs']);
    Route::post('/ops/tasks/{taskKey}/run', [OpsTaskController::class, 'run']);
    Route::get('/securities', [SecurityController::class, 'index']);
    Route::get('/securities/search', [SecurityController::class, 'search']);
    Route::get('/securities/{security:canonical_symbol}', [SecurityController::class, 'show']);
    Route::get('/securities/{security:canonical_symbol}/quote', [SecurityController::class, 'quote']);
    Route::get('/securities/{security:canonical_symbol}/daily-bars', [SecurityController::class, 'dailyBars']);
    Route::get('/indices', [IndexController::class, 'index']);
    Route::get('/indices/{index:code}/daily-bars', [IndexController::class, 'dailyBars']);
    Route::get('/news', [NewsController::class, 'index']);
    Route::get('/news/{article}', [NewsController::class, 'show']);
    Route::get('/events', [EventController::class, 'index']);
    Route::get('/events/{event}', [EventController::class, 'show']);
    Route::get('/event-chains', [EventChainController::class, 'index']);
    Route::get('/event-chains/{chain}', [EventChainController::class, 'show']);
    Route::get('/signals', [SignalController::class, 'index']);
    Route::get('/signals/dashboard', [SignalController::class, 'dashboard']);
    Route::get('/signals/{signal}', [SignalController::class, 'show']);
    Route::get('/strategy-workspaces/recommendations', [StrategyWorkspaceController::class, 'recommendations']);
    Route::get('/strategy-workspaces', [StrategyWorkspaceController::class, 'index']);
    Route::post('/strategy-workspaces', [StrategyWorkspaceController::class, 'store']);
    Route::get('/strategy-workspaces/{workspace}', [StrategyWorkspaceController::class, 'show']);
    Route::patch('/strategy-workspaces/{workspace}', [StrategyWorkspaceController::class, 'update']);
    Route::delete('/strategy-workspaces/{workspace}', [StrategyWorkspaceController::class, 'destroy']);
    Route::get('/strategy-workspaces/{workspace}/overview', [StrategyWorkspaceController::class, 'overview']);
    Route::get('/strategy-workspaces/{workspace}/recommendations', [StrategyWorkspaceController::class, 'recommendations']);
    Route::post('/strategy-workspaces/{workspace}/items', [StrategyWorkspaceController::class, 'storeItem']);
    Route::patch('/strategy-workspaces/{workspace}/items/{item}', [StrategyWorkspaceController::class, 'updateItem']);
    Route::delete('/strategy-workspaces/{workspace}/items/{item}', [StrategyWorkspaceController::class, 'destroyItem']);
    Route::get('/notification-templates', [NotificationTemplateController::class, 'index']);
    Route::post('/notification-templates', [NotificationTemplateController::class, 'store']);
    Route::get('/notification-templates/{template}', [NotificationTemplateController::class, 'show']);
    Route::patch('/notification-templates/{template}', [NotificationTemplateController::class, 'update']);
    Route::delete('/notification-templates/{template}', [NotificationTemplateController::class, 'destroy']);
    Route::get('/notification-channel-credentials', [NotificationChannelCredentialController::class, 'index']);
    Route::post('/notification-channel-credentials', [NotificationChannelCredentialController::class, 'store']);
    Route::get('/notification-channel-credentials/{credential}', [NotificationChannelCredentialController::class, 'show']);
    Route::patch('/notification-channel-credentials/{credential}', [NotificationChannelCredentialController::class, 'update']);
    Route::delete('/notification-channel-credentials/{credential}', [NotificationChannelCredentialController::class, 'destroy']);
    Route::post('/notification-channel-credentials/{credential}/verify', [NotificationChannelCredentialController::class, 'verify']);
    Route::get('/signal-operations/dashboard', [SignalOperationController::class, 'dashboard']);
    Route::post('/signal-operations/refresh', [SignalOperationController::class, 'refresh']);
    Route::post('/signal-operations/retry-backlog', [SignalOperationController::class, 'retryBacklog']);
    Route::get('/signal-deliveries', [SignalDeliveryController::class, 'index']);
    Route::get('/signal-deliveries/{delivery}', [SignalDeliveryController::class, 'show']);
    Route::post('/signal-deliveries/{delivery}/retry', [SignalDeliveryController::class, 'retry']);
    Route::get('/signal-subscriptions', [SignalSubscriptionController::class, 'index']);
    Route::post('/signal-subscriptions', [SignalSubscriptionController::class, 'store']);
    Route::get('/signal-subscriptions/{subscription}', [SignalSubscriptionController::class, 'show']);
    Route::patch('/signal-subscriptions/{subscription}', [SignalSubscriptionController::class, 'update']);
    Route::delete('/signal-subscriptions/{subscription}', [SignalSubscriptionController::class, 'destroy']);
    Route::post('/signal-subscriptions/{subscription}/test', [SignalSubscriptionController::class, 'test']);
});
